### ISSUE TITLE
icicle: aerosol source

### ISSUE THREAD

**Issue by pdziekan** [igfuw/libcloudphxx#139]
Don't we need a source of aerosol in order to reach a steady state in icicle icmw8_case1?

**Comment by slayoo** [comment]
Let's say that not having the source terms, we can only achieve a steady state in which the drizzle does not reach the ground level - i.e. it evaporates below the cloud.

**Comment by slayoo** [comment]
Anyhow, this is a valid TODO item, at least if one wants to compare the results with bulk schemes as they implicitly assume an infinite source of aerosols.

**Comment by pdziekan** [comment]
imlemented
