### ISSUE TITLE
Store rw3 instead of rw2 to improve performance?

### ISSUE THREAD

**Issue by pdziekan** [igfuw/libcloudphxx#141]
Condensation function uses rw^3 a lot. Storing it instead of rw^2 (which now has to be converted to rw^3 and rd^3 to rd^2) would improve performance of condensation, which is bottleneck of simulations that use both cloudphxx and mpdata.

**Comment by slayoo** [comment]
rw^2 was chosen following the original SDM implementation of Shima as it reportedly reduces stiffness of the drop growth equation. I believe we can safely keep it, but indeed calculating once the rw3 and storing it would improve performance as it is calculated multiple times now (incl. chemistry).
