### ISSUE TITLE
particles: order of processes (sedimentation vs. boundary cond)

### ISSUE THREAD

**Issue by slayoo** [igfuw/libcloudphxx#180]
Currently, the particle processes are applied in the following order:
- hskpng_ijk
- advection
- bcond (incl. flagging out-of-domain particles)
- sedimentation

Consequently, once a particle gets out of domain due to sedimentation, it is still advected once before being recycled. Luckly, in icicle the velocities are still valid half a grid cell below z0 but we cannot rely on it.

**Comment by pdziekan** [comment]
fixed
