### ISSUE TITLE
icicle: invalid formula for AMPL(w_max)?

### ISSUE THREAD

**Issue by slayoo** [igfuw/libcloudphxx#181]
the formula stems from differentiating the stream function, which gives

AMPL ~ w_max \* X / 2 / pi

and this is what is e.g. in KiD

While in icicle the "2" factor is missing.

This causes velocities of ~1 m/s to appear with the default w_max of 0.6 m/s

**Comment by pdziekan** [comment]
That was fixed. Paper tests results differ from published ones now.
