### ISSUE TITLE
master not compiling

### ISSUE THREAD

**Issue by trontrytel** [igfuw/libcloudphxx#385]
The current master givens me the same errors as here: 

https://travis-ci.org/igfuw/libcloudphxx/jobs/614974117?utm_medium=notification&utm_source=github_status

Is there any hope of fixing this?

**Comment by pdziekan** [comment]
Please use the sgs_kin_surf_flux branch from my repo.
It will be merged into master asap.

niedz., 24 lis 2019 o 04:10 Anna Jaruga <notifications@github.com>
napisał(a):

**Comment by trontrytel** [comment]
> Please use the sgs_kin_surf_flux branch from my repo. It will be merged into master asap

Thanks! (Luckily I kept my old branch before pulling from upstream. So I panicked but only briefly)

**Comment by trontrytel** [comment]
@pdziekan  - The branch was merged to UWLCM. So this one should be resolved?
