### ISSUE TITLE
sudo make install mystery - OSX

### ISSUE THREAD

**Issue by djarecka** [igfuw/libcloudphxx#73]
Sudo make install does not do the same as cp libcloudphxx.so
It leads to segfault when calling from python!

Might be related to issue #47

**Comment by slayoo** [comment]
```
slayoo-local@skua:~/devel/libcloudphxx/build/bindings$ sudo make install
[ 80%] Built target cloudphxx_lgrngn
[ 80%] Built target git_revision.h
[100%] Built target cloudphxx
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/python2.7/dist-packages/libcloudphxx.so
-- Removed runtime path from "/usr/local/lib/python2.7/dist-packages/libcloudphxx.so"
```

Perhaps the last line is a hint!

**Comment by djarecka** [comment]
works after cp:
sudo cp bindings/python/libcloudphxx.so /Library/Python/2.7/site-packages/libcloudphxx.so

**Comment by slayoo** [comment]
It seems that it was caused by a leftover copy of libcloudph_lgrngn.so in /usr/local, while the main installation was in /usr 

Currently, it is not reproducible.
